#!/usr/bin/env ruby
require 'rubygems'
require "daemons"
require "daemons/rails/config"

config = Daemons::Rails::Config.new("spotify_controller", File.dirname(__FILE__) + "/../../")

Daemons.run File.dirname(__FILE__) + "/spotify_controller.rb", config.to_hash